CREATE TABLE comments(
    id SERIAL PRIMARY KEY,
    image_id INT NOT NULL,
    comment VARCHAR(300) NOT NULL,
    username VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
